FROM nvcr.io/nvidia/pytorch:21.02-py3

RUN apt-get update && \
    apt-get install --yes --no-install-recommends \
      espeak-ng

COPY download/amd64/ /download/

ARG TTS_VERSION=0.0.13.2

RUN --mount=type=cache,id=python-run,target=/var/apt/cache \
    pip install -f /download "TTS==${TTS_VERSION}"

ENV LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4

ENTRYPOINT ["tts"]