#!/usr/bin/env bash
args=()

while [[ -n "$1" ]]; do
    if [[ "$1" == '--update' ]]; then
        # Update Docker image
        docker pull synesthesiam/coqui-tts
    else
        args+=("$1")
    fi

    shift 1
done

docker run \
       -it \
       -e "HOME=${HOME}" \
       -v "$HOME:${HOME}" \
       -w "${PWD}" \
       -p 5002:5002 \
       --user "$(id -u):$(id -g)" \
       --entrypoint '/app/bin/tts-server' \
       synesthesiam/coqui-tts \
       "${args[@]}"
